# Use the official Node.js image as the base image
FROM node:latest

# Set the working directory to the backend folder
WORKDIR /app/backend

# Copy package.json and package-lock.json to the working directory
COPY package.json .
COPY package-lock.json .

# Install dependencies
RUN npm install

# Copy the rest of the backend files
COPY . .

# Expose the port that your backend application is running on
EXPOSE 8000

# Command to run the backend application
CMD ["node", "server.js"]
